#!/bin/bash
index=0
for mode in {1..6}
do
	for rd in {0..3}
	do
	cp Run.sh run_mode''$mode''_rd''$rd''.sh
	sed -i '5s@.*@WebVRPort='$((index+8100))'@' ./run_mode''$mode''_rd''$rd''.sh
	((index++))
	sed -i '6s@.*@VideoPath="./Nguyenidol/ERP_mode_'$mode'_DrivingInCity_rd'$rd'.mp4"@' ./run_mode''$mode''_rd''$rd''.sh
	done
done
